apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-app
  labels:
    app: abc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc-app
  template:
    metadata:
      labels:
        app: abc-app
    spec:
      containers:
      - name: abc-app
        image: "coderdevops123/abc-service:latest"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: abc-service
spec:
  type: LoadBalancer
  selector:
    app: abc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

